-- Migration V7: Create jobs table and seed initial job postings

CREATE TABLE jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_name VARCHAR(150) NOT NULL,
    company_logo VARCHAR(255),
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    requirements TEXT,
    benefits TEXT,
    city VARCHAR(50) NOT NULL,
    address_detail VARCHAR(255),
    employment_type VARCHAR(30) NOT NULL,
    experience_level VARCHAR(30) NOT NULL,
    salary_min NUMERIC(15, 2),
    salary_max NUMERIC(15, 2),
    is_negotiable_salary BOOLEAN DEFAULT FALSE,
    currency VARCHAR(10) DEFAULT 'VND',
    status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
    views_count INT DEFAULT 0,
    expired_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_jobs_search ON jobs(status, city, employment_type, experience_level);
CREATE INDEX idx_jobs_created_at ON jobs(created_at DESC);

-- Seed initial public jobs data
INSERT INTO jobs (id, company_name, company_logo, title, description, requirements, benefits, city, address_detail, employment_type, experience_level, salary_min, salary_max, is_negotiable_salary, currency, status, views_count, created_at)
VALUES 
(
    'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    'TechNova Solutions',
    'https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=120&auto=format&fit=crop&q=80',
    'Senior Frontend Engineer (React/TypeScript)',
    'Chúng tôi tìm kiếm Senior Frontend Engineer am hiểu sâu sắc về React 18+, TypeScript và tối ưu hóa hiệu năng giao diện Web.',
    'Có ít nhất 3 năm kinh nghiệm làm việc với React. Thạo TailwindCSS/CSS Modules. Sử dụng thành thạo Git & RESTful API.',
    'Lương tháng 13, thưởng dự án. Bảo hiểm Healthcare cao cấp. 15 ngày phép năm.',
    'HCM',
    'Tầng 8, Tòa nhà Bitexco, Quận 1, TP. Hồ Chí Minh',
    'FULL_TIME',
    'THREE_TO_FIVE',
    25000000.00,
    40000000.00,
    FALSE,
    'VND',
    'PUBLISHED',
    142,
    CURRENT_TIMESTAMP - INTERVAL '2 days'
),
(
    'b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e',
    'DataStream Global',
    'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=120&auto=format&fit=crop&q=80',
    'Java Backend Developer (Spring Boot / Microservices)',
    'Tham gia phát triển hệ thống tài chính phân tán quy mô lớn sử dụng Spring Boot 3, Kafka và PostgreSQL.',
    'Kinh nghiệm 2+ năm với Java / Spring Boot. Hiểu biết về REST API, JPA Hibernate, Docker và CI/CD.',
    'Môi trường làm việc Hybrid flex. Thưởng theo KPI quý. Phụ cấp laptop cá nhân.',
    'HN',
    'Số 1 Thái Hà, Đống Đa, Hà Nội',
    'HYBRID',
    'TWO_TO_THREE',
    20000000.00,
    32000000.00,
    FALSE,
    'VND',
    'PUBLISHED',
    98,
    CURRENT_TIMESTAMP - INTERVAL '1 day'
),
(
    'c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f',
    'CyberNexus AI',
    'https://images.unsplash.com/photo-1516876437184-593fda40c7ce?w=120&auto=format&fit=crop&q=80',
    'DevOps & Cloud Security Specialist',
    'Xây dựng và vận hành hạ tầng Cloud Kubernetes trên AWS / GCP. Tự động hóa quy trình CI/CD cho các ứng dụng ATS AI.',
    'Thành thạo Kubernetes, Terraform, Docker, Jenkins/GitHub Actions. Có chứng chỉ AWS SA là lợi thế.',
    'Lương thỏa thuận xứng đáng. Làm việc Remote 100%. Được hỗ trợ phí thi chứng chỉ quốc tế.',
    'DN',
    'Tòa nhà Công nghệ cao, Quận Hải Châu, Đà Nẵng',
    'REMOTE',
    'THREE_TO_FIVE',
    30000000.00,
    50000000.00,
    TRUE,
    'VND',
    'PUBLISHED',
    215,
    CURRENT_TIMESTAMP - INTERVAL '3 days'
),
(
    'd4e5f6a7-b89c-0d1e-2f3a-4b5c6d7e8f9a',
    'InnoSoft Vietnam',
    'https://images.unsplash.com/photo-1551434678-e076c223a692?w=120&auto=format&fit=crop&q=80',
    'Junior Fullstack Web Developer (Node.js & Vue.js)',
    'Phát triển ứng dụng Web thương mại điện tử thế hệ mới cho các đối tác Nhật Bản và Châu Âu.',
    'Tốt nghiệp đại học chuyên ngành CNTT. Nắm vững JavaScript/TypeScript, HTML/CSS. Yêu thích thử thách công nghệ mới.',
    'Được đào tạo bài bản từ Senior Tech Lead. Thưởng hoàn thành dự án.',
    'CT',
    'Khu Công nghệ thông tin tập trung, Quận Ninh Kiều, Cần Thơ',
    'FULL_TIME',
    'ONE_TO_TWO',
    12000000.00,
    18000000.00,
    FALSE,
    'VND',
    'PUBLISHED',
    64,
    CURRENT_TIMESTAMP - INTERVAL '5 hours'
),
(
    'e5f6a7b8-9c0d-1e2f-3a4b-5c6d7e8f9a0b',
    'NextGen Mobility',
    'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=120&auto=format&fit=crop&q=80',
    'UI/UX Designer (Product Design)',
    'Thiết kế giao diện và trải nghiệm người dùng cho ứng dụng di động tuyển dụng và quản lý nhân sự ATS.',
    'Kinh nghiệm 2+ năm thiết kế Figma. Biết sử dụng Design Systems, Auto-layout. Có Portfolio sản phẩm thực tế.',
    'Trang bị Macbook Pro M2. Môi trường sáng tạo trẻ trung, tự do.',
    'HP',
    'Số 12 Lê Hồng Phong, Ngô Quyền, Hải Phòng',
    'FULL_TIME',
    'TWO_TO_THREE',
    15000000.00,
    25000000.00,
    FALSE,
    'VND',
    'PUBLISHED',
    89,
    CURRENT_TIMESTAMP - INTERVAL '4 days'
);
