import { Job } from '../types';

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior Backend Engineer',
    company: 'Fintech Solutions VN',
    location: 'Hà Nội',
    salary: 'Up to $2,500',
    tags: ['Java', 'Spring Boot', 'PostgreSQL'],
    postedAt: '2 giờ trước',
    matchScore: 98,
  },
  {
    id: '2',
    title: 'Frontend Developer (ReactJS)',
    company: 'Tech Innovators',
    location: 'Hồ Chí Minh',
    salary: '$1,000 - $1,500',
    tags: ['React', 'TypeScript', 'Tailwind CSS'],
    postedAt: '5 giờ trước',
    matchScore: 95,
  },
  {
    id: '3',
    title: 'AI/ML Engineer',
    company: 'NextGen AI',
    location: 'Đà Nẵng (Hybrid)',
    salary: 'Thỏa thuận',
    tags: ['Python', 'TensorFlow', 'LLMs'],
    postedAt: '1 ngày trước',
    matchScore: 92,
  },
  {
    id: '4',
    title: 'Product Manager',
    company: 'E-commerce Group',
    location: 'Hà Nội',
    salary: 'Up to $3,000',
    tags: ['Agile', 'Scrum', 'Data Analysis'],
    postedAt: '2 ngày trước',
    matchScore: 88,
  },
  {
    id: '5',
    title: 'DevOps Engineer',
    company: 'Cloud Native JSC',
    location: 'Remote',
    salary: '$1,500 - $2,200',
    tags: ['AWS', 'Kubernetes', 'CI/CD'],
    postedAt: '3 ngày trước',
    matchScore: 85,
  },
  {
    id: '6',
    title: 'UI/UX Designer',
    company: 'Creative Agency',
    location: 'Hồ Chí Minh',
    salary: 'Up to $1,200',
    tags: ['Figma', 'Prototyping', 'User Research'],
    postedAt: '3 ngày trước',
    matchScore: 80,
  }
];
